apiVersion: v1
kind: Service
metadata:
  name: patient-service-db
  namespace: patient-management
spec:
  type: ClusterIP
  selector:
    app: patient-service-db
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
