apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: patient-management
type: Opaque
stringData:
  POSTGRES_DB: db
  POSTGRES_USER: admin_user
  POSTGRES_PASSWORD: password
  SPRING_DATASOURCE_USERNAME: admin_user
  SPRING_DATASOURCE_PASSWORD: password
